# These are supported funding model platforms

github: orioninsist
patreon: orioninsist
open_collective: # Replace with a single Open Collective username
ko_fi: orioninsist
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: orioninsist
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: # Replace with a single Polar username
buy_me_a_coffee: orioninsist
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
